[book]
authors = ["ImplFerris"]
language = "en"
multilingual = false
src = "src"
title = "Rusty Riddler"

[preprocessor.quiz]
cache-answers = false
fullscreen = true

[output.html]
git-repository-url = "https://github.com/ImplFerris/RustyRiddler"
